"""
Download and prepare GPT-4 test data for evaluation.

This script downloads available datasets with GPT-4 or modern AI text
and prepares them for testing the Joseph detector.
"""

import json
import logging
from pathlib import Path

import pandas as pd
from datasets import load_dataset
from tqdm import tqdm

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)


def download_gpt_wiki_intro(output_dir, max_samples=1000):
    """
    Download GPT-generated Wikipedia intros.

    This dataset contains Wikipedia introductions written by both humans
    and generated by GPT models.
    """
    logger.info("Downloading GPT-wiki-intro dataset...")

    try:
        dataset = load_dataset("aadityaubhat/GPT-wiki-intro", split="train")  # nosec B615

        logger.info(f"Loaded {len(dataset)} samples")

        # Prepare data
        data = []
        for item in tqdm(dataset.select(range(min(max_samples, len(dataset)))), desc="Processing"):
            # Human text
            data.append(
                {
                    "text": item["wiki_intro"],
                    "label": 0,  # human
                    "source": "wikipedia",
                    "model": "human",
                }
            )

            # AI text
            data.append(
                {
                    "text": item["generated_intro"],
                    "label": 1,  # AI
                    "source": "wikipedia",
                    "model": "gpt",
                }
            )

        df = pd.DataFrame(data)

        # Save
        output_file = output_dir / "gpt_wiki_test.parquet"
        df.to_parquet(output_file)
        logger.info(f"Saved {len(df)} samples to {output_file}")

        # Print stats
        logger.info(f"Human samples: {(df['label'] == 0).sum()}")
        logger.info(f"AI samples: {(df['label'] == 1).sum()}")

        return df

    except Exception as e:
        logger.error(f"Failed to download dataset: {e}")
        return None


def create_manual_gpt4_samples(output_dir):
    """
    Template for adding your own GPT-4 samples.

    If you have access to GPT-4/5, generate samples here.
    """
    logger.info("Creating manual GPT-4 sample file template...")

    template = {
        "instructions": "Add your GPT-4/5 generated texts here",
        "format": {
            "text": "The generated text",
            "label": 1,  # 1 for AI, 0 for human
            "model": "gpt-4 or gpt-5",
            "prompt": "The prompt used (optional)",
        },
        "samples": [
            {
                "text": "Replace this with actual GPT-4 generated text",
                "label": 1,
                "model": "gpt-4",
                "prompt": "Write about climate change",
            },
            # Add more samples here
        ],
    }

    output_file = output_dir / "manual_gpt4_template.json"
    with open(output_file, "w") as f:
        json.dump(template, f, indent=2)

    logger.info(f"Created template at {output_file}")
    logger.info("Edit this file to add your GPT-4/5 samples, then run convert script")


def main():
    """Main download script."""
    # Setup paths
    project_root = Path(__file__).parent.parent
    output_dir = project_root / "data" / "gpt4_test"
    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("=" * 60)
    logger.info("GPT-4 Test Data Downloader")
    logger.info("=" * 60)

    # Download available datasets
    logger.info("\n1. Downloading public datasets...")
    download_gpt_wiki_intro(output_dir, max_samples=500)

    # Create template for manual samples
    logger.info("\n2. Creating manual sample template...")
    create_manual_gpt4_samples(output_dir)

    logger.info("\n" + "=" * 60)
    logger.info("Download complete!")
    logger.info(f"Data saved to: {output_dir}")
    logger.info("\nNext steps:")
    logger.info("1. Add your own GPT-4/5 samples to manual_gpt4_template.json")
    logger.info("2. Run evaluation: python scripts/evaluate_on_gpt4.py")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
